### ISSUE TITLE
Images broke on the README

### ISSUE THREAD

**Issue by dominichayesferen** [explorer7-team/source#3]
Probably a consequence of making the repository public + how the images were inserted, but the images on the README are all dead links.

e.g.: Logo currently points to https://github.com/user-attachments/assets/10465c11-481a-4403-aeef-19149a776f17, which is dead (same with every screenshot)

**Comment by Erizur** [comment]
![image](https://github.com/user-attachments/assets/36f583af-c9e1-4c8d-a21a-c4e9b9c530df)
They are not broken.

**Comment by kawapure** [comment]
![image](https://github.com/user-attachments/assets/c02f3a9d-af84-43ad-9a66-570151b0f8fc)

**Comment by dominichayesferen** [comment]
![image](https://github.com/user-attachments/assets/6ee28d4b-a67a-4248-8051-26daea50a509)

that's weird.

**Comment by Erizur** [comment]
Seems like it's related to permissions. A fix will be done asap.

**Comment by dominichayesferen** [comment]
Yeah, it's probably because your IPs are known by GitHub to be used by accounts that could access the screenshots beforehand when they were private... or something along those lines.

Ah well, easy enough to fix by just dragging and dropping the images back into place.

**Comment by Erizur** [comment]
Updated.
